export * from './Flower';
export * from './Land';
export * from './Person1';
export * from './Person2';
export * from './Environment';
export * from './IceCream';
export * from './Platform';
export * from './SteppingBox';
export * from './Door';